name: invoice_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.3.0
  pin_code_text_field: ^1.8.0
  introduction_screen: ^3.0.2
  animated_bottom_navigation_bar: ^1.1.0
  image_picker: ^0.8.7+1
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  equatable: ^2.0.5
  easy_localization: ^3.0.1
  connectivity_plus: ^3.0.2
  alice: ^0.3.2
  font_awesome_flutter: ^10.4.0
  pretty_dio_logger: ^1.1.1
  dotted_border: ^2.0.0+3
  shared_preferences: ^2.0.15
  device_preview: ^1.1.0
  flutter_bloc: ^8.1.1
  syncfusion_flutter_sliders: ^20.3.57
  synchronized: ^3.0.0+3
  dartz: ^0.10.1
  dio: ^4.0.6
  retrofit: ^3.3.1
  injectable: ^1.5.3
  json_annotation: ^4.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner:
  json_serializable: '>4.4.0'
  injectable_generator: ^1.5.4


flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/locale/

